apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-graphql-deployment
  labels:
    app: docker-k8s-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-graphql
  template:
    metadata:
      labels:
        app: docker-k8s-graphql
    spec:
      containers:
        - name: docker-k8s-graphql
          image: akshatjain010/graphql:deleteBook_v2
          ports:
            - containerPort: 8081